### ISSUE TITLE
lgb.dump fails for larger models

### ISSUE THREAD

**Issue by rgranvil** [Microsoft/LightGBM#1086]
@guolinke In the latest version, the lgb.dump R function produces an empty character vector for larger models.  The largest model that worked successfully for me had a dump file of around 2^20 characters, which can be hit pretty easily (600 rounds, 7 num_leaves).  

If it helps, I can post reproducible example when I get home.

**Comment by guolinke** [comment]
@rgranvil it is caused by the latest commit ?

**Comment by rgranvil** [comment]
@guolinke I'm not sure exactly which commit caused it.  I was comparing v2.0.10 to the current master branch, so it was something in that range.

**Comment by guolinke** [comment]
@rgranvil can you check it before and after this commit: 619c06d8f85149cd437df96cf9de9f22f7d48e8d ?

**Comment by guolinke** [comment]
@rgranvil 
can you also try set these two lines:
https://github.com/Microsoft/LightGBM/blob/master/src/lightgbm_R.cpp#L607
https://github.com/Microsoft/LightGBM/blob/master/src/lightgbm_R.cpp#L629
to ```if (out_len <= R_AS_INT(buffer_len)) {```

**Comment by rgranvil** [comment]
@guolinke I confirmed that commit was causing the issue and modifying those two lines seems to fix the problem.

**Comment by guolinke** [comment]
@rgranvil thanks, I just fix it in the latest commit

**Comment by guolinke** [comment]
@rgranvil close. feel free to reopen if it doesn't work.

**Comment by rgranvil** [comment]
@guolinke I get the following errors when trying to install the R-package of the latest commit:


/tmp/RtmpZNfk4j/R.INSTALL64c02f214618/lightgbm/src/src/lightgbm_R.cpp: In function ‘LGBM_SER* EncodeChar(LGBM_SE, const char*, LGBM_SE, LGBM_SE)’:
/tmp/RtmpZNfk4j/R.INSTALL64c02f214618/lightgbm/src/src/lightgbm_R.cpp:41:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (R_AS_INT(buf_len) < str_len) { return dest; }
                           ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-ignored-attributes" [enabled by default]

**Comment by guolinke** [comment]
@rgranvil sorry, it is a warning. I just fix it.

**Comment by rgranvil** [comment]
@guolinke The warning is gone, but I run into the original problem with lgb.dump of large models.

**Comment by guolinke** [comment]
@rgranvil really? I don't think that commit will break the large model...

**Comment by rgranvil** [comment]
@guolinke Yes, I just pulled from the master branch and tested again. Here is a reproducible example:

Code:
```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)
model <- lgb.train(params,
                   dtrain,
                   min_data = 1,
                   nrounds = 600,
                   num_leaves = 8,
                   learning_rate = .01)
lgb.dump(model)
```

Output:
```r
> lgb.dump(model)
[1] ""
```

**Comment by guolinke** [comment]
@rgranvil can you try it again ? I believe it is fixed by this commit: 63b60825ba90b348e8100d0f9bb23c14e5bb857d

**Comment by rgranvil** [comment]
@guolinke I just tried it again and get the same problem.

**Comment by guolinke** [comment]
@rgranvil I just try it. and the result is fine:
![image](https://user-images.githubusercontent.com/16040950/33511087-dc397ad2-d74f-11e7-8d1b-db4a6bd24750.png)



can you check your installation ?

**Comment by rgranvil** [comment]
@guolinke Strange.  I still get the same blank output:
```r
> lgb.dump(model)
[1] ""
```
I tried installing from the current master and from 63b60825ba90b348e8100d0f9bb23c14e5bb857d.  I tested it on both Linux and Windows machines.    I also tried completely removing the lightgbm R package prior to installation.  Everything gives the same result.  I don't see any errors/warnings in the installation.  Anything else I should try?

**Comment by guolinke** [comment]
@Laurae2 can you help to test this as well?

**Comment by Laurae2** [comment]
@guolinke @rgranvil Installed latest LightGBM (c2191aa), same issue as OP but this is corrected by doing this:

```r
> library(lightgbm)
Loading required package: R6
> data(agaricus.train, package = "lightgbm")
> train <- agaricus.train
> dtrain <- lgb.Dataset(train$data, label = train$label)
> data(agaricus.test, package = "lightgbm")
> test <- agaricus.test
> dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
> params <- list(objective = "regression", metric = "l2")
> valids <- list(test = dtest)
> model <- lgb.train(params,
+                    dtrain,
+                    min_data = 1,
+                    nrounds = 600,
+                    num_leaves = 8,
+                    learning_rate = .01)
Loading required package: Matrix
> lgb.dump(model)
[1] ""
> lgb.dump(model, num_iteration = 1)
(truncated long output...)
> model$dump_model(num_iteration = 1)
(truncated long output...)
```

**Comment by guolinke** [comment]
@rgranvil please try the latest code

**Comment by rgranvil** [comment]
@guolinke Works well now, thanks!
