### ISSUE TITLE
"Check failed: (best_split_info.left_count) > (0)" in forced_split mode

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#4286]
I met this when using "forcedsplit_filename". following data and code will repeat this issue.  The only clue I can provide is that  the num of nan in features may affect some split process with forcedsplits.

lgbversion:3.2.1
xdata:
[checkdata.zip](https://github.com/microsoft/LightGBM/files/6477570/checkdata.zip)

```
import lightgbm as lgb
import numpy as np
import json
x=np.load($xdata)
y=np.random.rand(x.shape[0])
forcesplit_json={'feature':1,'threshold':0.3,'right':{'feature':1,'threshold':0.7}}
tmppath=$somerandpath
with open(tmppath,'w') as f:
    json.dump(forcesplit_json,f)
params={'objective':'mse','forcedsplit_filepath':tmppath,'max_bin':64}
ds=lgb.Dataset(data=x,label=y,params=params)
lgb.train(ds,params=params)

```

**Comment by shiyu1994** [comment]
This is due to a bug in `GatherInfoForThresholdNumericalInner`, the `<` in line 575 here should be `<=`.
https://github.com/microsoft/LightGBM/blob/da3465cbf1d1cf43e0d14908f110814e960905bc/src/treelearner/feature_histogram.hpp#L573-L577
I'll check other methods related to force splits to avoid similar bugs.

**Comment by shiyu1994** [comment]
@aprilffff Could you please verify that the problem is resolved in the latest master branch for your real case application? You may need to build lightgbm from the latest master branch source code according to https://github.com/microsoft/LightGBM/tree/master/python-package#install-from-github. Thanks!

**Comment by shiyu1994** [comment]
I'm sorry. But it seems that this error is the same as in the title of this issue?

**Comment by aprilffff** [comment]
> I'm sorry. But it seems that this error is the same as in the title of this issue?

oh, right, my fault

**Comment by StrikerRUS** [comment]
@aprilffff Could you please double check with the latest code from `master`? You can use nightly builds if you don't want to build from sources.

I just run your example with the latest version of LightGBM on my machine without any errors.
```
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015380 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 448
[LightGBM] [Info] Number of data points in the train set: 500000, number of used features: 7
[LightGBM] [Info] Start training from score 0.499443
```

P.S. there were two typos in the original reproducible example, I've corrected them.
1. `params` argument comes before `train_set`: `lgb.train(params=params, train_set=ds)`.
2. `forcedsplit_filepath` should be `forcedsplits_filename`.

**Comment by aprilffff** [comment]
> @aprilffff Could you please double check with the latest code from `master`? You can use nightly builds if you don't want to build from sources.
> 
> I just run your example with the latest version of LightGBM on my machine without any errors.
> 
> ```
> [LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015380 seconds.
> You can set `force_col_wise=true` to remove the overhead.
> [LightGBM] [Info] Total Bins 448
> [LightGBM] [Info] Number of data points in the train set: 500000, number of used features: 7
> [LightGBM] [Info] Start training from score 0.499443
> ```
> 
> P.S. there were two typos in the original reproducible example, I've corrected them.
> 
> 1. `params` argument comes before `train_set`: `lgb.train(params=params, train_set=ds)`.
> 2. `forcedsplit_filepath` should be `forcedsplits_filename`.

Did you make new revises other than what @shiyu1994 did in GatherInfoForThresholdNumericalInner? After shiyu1994's revise, this bug truly disappeared on the mini example  I provided, but still got the same bug on my real application data(over 10million samples,cannot share). And after many trials, I'm still not able to build another mini sample to replicate. So,  we might could close this issue for now, and I'll reopen it once I successfully get a sample to replicate this bug. What do you think?

**Comment by shiyu1994** [comment]
It is OK to keep this issue. I can spend some more time these days to check if there're other problems in the code related to forced splits.

**Comment by pseudotensor** [comment]
FYI I still get this on master as of 2370961ae01a7332f6356bda311897b35e67e362

```
 File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/sklearn.py", line 849, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/sklearn.py", line 712, in fit
    self._Booster = train(params, train_set,
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/engine.py", line 256, in train
    booster.update(fobj=fobj)
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/basic.py", line 2939, in update
    _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /workspace/LightGBM/src/treelearner/serial_tree_learner.cpp, line 653 .
```
